services:
  postgres:
    image: postgres:17
    container_name: relojoaria-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: relojoaria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - relojoaria_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d relojoaria -h localhost -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5

  relojoaria-digital:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: relojoaria
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/relojoaria?sslmode=disable"  # <—
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "root"
      SERVER_PORT: "8080"

volumes:
  relojoaria_pgdata:
